
name: motocam2
description: Computational photography engine for Motorola Edge 30 Neo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  image: ^4.2.0
  path_provider: ^2.1.3
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
